---
# defaults file for splunk_uf
splunk_forwarder_user: "splunk"
splunk_forwarder_group: "splunk"
splunk_forwarder_uid: "10011"
splunk_forwarder_gid: "10011"
splunk_url: "https://download.splunk.com/products/universalforwarder/releases/8.2.1/linux"
splunk_forwarder_rpm: "splunkforwarder-8.2.1-ddff1c41e5cf-linux-2.6-x86_64.rpm"
splunk_forwarder_deb: "splunkforwarder-8.2.1-ddff1c41e5cf-linux-2.6-amd64.deb"
splunk_rpm: "{{ splunk_url }}/{{ splunk_forwarder_rpm }}"
splunk_deb: "{{ splunk_url }}/{{ splunk_forwarder_deb }}"
#splunk_deb_checksum: "md5:4adc5272d40d148b1d7540187bebae2d"
#splunk_rpm_checksum: "md5:a6c2dfcd0e6bed3323999f90fe4d9893"


# These may be removed at some point, but they are placeholders so I don't forget to set them
#splunk_forwarder_indexer: "splunk-indexer:9997"
#splunk_forwarder_index: "default"
#splunk_forwarder_sourcetype: "nginx"

splunk_forwarder_logs:
  - /var/log/nginx/access.log
  - /var/log/nginx/error.log
