---
 - name: Download and Install Commvault Agent
   hosts: linux1
   become: yes

   vars:
    source_folder: /Users/obobko/Desktop/keys/ansible/CommvaultPkg-Linux-FS-el8-x64-latest.rpm
    destin_folder: /home/ec2-user

   tasks:
   - name: Install Libraries
     yum:
       name: libnsl
       name: ncurses-compat-libs
       name: kexec-tools
       name: pciutils
       name: psmisc
       name: net-tools
       state: latest

   #- name: Dir list and write to file
   #  shell:
   #      "/tmp/test.sh "
   #  register: is_commvault_installed
   #  ignore_errors: yes
  
   #- debug: msg="{{is_commvault_installed.stdout}}"

   #- name: Download Commvault Agent for Centos
   #  get_url:
   #   url: https://isapp-web-storage.softservecom.com/commvault/CommvaultPkg-Linux-FS-el7-x64-latest.rpm 
   #   dest: /usr/local/src/
   #   validate_certs: no
   #  environment:
   #   http_proxy: http://proxy.softservecom.com:8080
   #   https_proxy: http://proxy.softservecom.com:8080
   #  when: ansible_distribution == 'Centos'
     
   #- name: Download Commvault Agent for RedHat
   #  get_url:
   #   url: https://isapp-web-storage.softservecom.com/commvault/CommvaultPkg-Linux-FS-el8-x64-latest.rpm 
   #   dest: /usr/local/src/
   #   validate_certs: no
   #  environment:
   #   http_proxy: http://proxy.softservecom.com:8080
   #   https_proxy: http://proxy.softservecom.com:8080
   #  when: ansible_distribution == 'RedHat'

   - name: Copy MyHomePage to Servers
     copy: src={{ item }} dest={{ destin_folder }} mode=755
     loop:
        - "CommvaultPkgFra-Linux-FS-x64-el8-11.24.23.rpm"

   - name: Install Commvault Agent
     yum: 
       name: /home/ec2-user/CommvaultPkg-Linux-FS-el8-x64-latest.rpm
       state: installed
     #ignore_errors: yes
     #when: is_commvault_installed == 0

   - name: Start Commvault Agent
     service: name=commvault.service state=started enabled=yes
     ignore_errors: yes

   - name: Allow new incoming TCP port for Commvault
     ansible.builtin.iptables:
       chain: INPUT
       protocol: tcp
       destination_port: '8400'
       ctstate: NEW
       jump: ACCEPT

   - name: Allow new incoming TCP port for Commvault
     ansible.builtin.iptables:
       chain: INPUT
       protocol: tcp
       destination_port: '8403'
       ctstate: NEW
       jump: ACCEPT

   - name: Save iptables
     shell: service iptables save
   - name: Restart iptables
     service: name=iptables state=restarted
