---
 - name: Download and Install Commvault Agent
   hosts: all
   become: yes

   tasks:
   - name: Install Libraries
      yum:
        name: '{{ item }}'
        state: present
        update_cache: True
      with_items:
        - libnsl 
        - ncurses-compat-libs 
        - kexec-tools 
        - pciutils 
        - psmisc 
        - net-tools

   - name: Download Commvault Agent for CentOS
     get_url:
      url: https://isapp-web-storage.softservecom.com/commvault/CommvaultPkg-Linux-FS-el8-x64-latest.rpm
      dest: /usr/local/src/
      validate_certs: no
     environment:
      http_proxy: http://proxy.softservecom.com:8080
      https_proxy: http://proxy.softservecom.com:8080
     #when: ansible_distribution == 'CentOS'

   - name: Install Commvault Agent
     yum: name=/usr/local/src/CommvaultPkg-Linux-FS-x64-latest.rpm state=present
     ignore_errors: yes
     #when: is_commvault_installed == 0

   - name: Start Commvault Agent
     service: name=commvault.service state=started enabled=yes
     ignore_errors: yes

   - name: Allow new incoming TCP port for Commvault
     ansible.builtin.iptables:
       chain: INPUT
       protocol: tcp
       destination_port: '8400'
       ctstate: NEW
       jump: ACCEPT

   - name: Save iptables
     shell: service iptables save
   - name: Restart iptables
     service: name=iptables state=restarted

   - name: Check Commvault service status
    shell: systemctl status commvault.service 
    register: command_output
    
  - debug: 
           var: command_output.stdout_lines

  - name: Check Commvault All status
    shell: commvault -all status
    register: command_output
    
  - debug: 
           var: command_output.stdout_lines

