---
- name: Install default Apache server
  hosts: aws_hosts
  become: yes
  
  vars:
    source_file: /Users/obobko/Desktop/keys/ansible/MyWebSite/index.html
    destin_file: /var/www/html

  tasks:
  - name: Check LinuxOS Family
    debug: var="ansible_os_family" 
 
  - block: # ====RedHat==== 

      - name: Install Apache Web Server for RedHat
        yum:  name=httpd state=latest
        when: ansible_os_family == "RedHat"

      - name: Copy MyHomePage to Servers
        copy: src={{ source_file }} dest={{ destin_file }} mode=0555
        notify: Restart Apache in RedHat
      
      - name: Start Apache and Enable it on the every boot on RedHat
        service: name=httpd state=started enabled=yes
    when: ansible_os_family == "RedHat"

  - block: #====Debian====

      - name: Install Apache Web Server for Debian
        apt:  name=apache2 state=latest
        when: ansible_os_family == "Debian"

      - name: Copy MyHomePage to Servers
        copy: src={{ source_file }} dest={{ destin_file }} mode=0555
        notify: Restart Apache in Debian

      - name: Start Apache and Enable it on the every boot on Debian
        service: name=apache2 state=started enabled=yes
    when: ansible_os_family == "Debian"

  handlers:
  - name: Restart Apache in RedHat
    service: name=httpd state=restarted

  - name: Restart Apache in Debian
    service: name=apache2 state=restarted
