---
- name: My Playbook
  hosts: aws_hosts
  become: yes

  vars:
   mytext: "hello from shaman"

  tasks:
  - name: Ping test
    ping:

  #- name: Unregister Server from load balancer
  #  shell: echo This Server {{ inventory_hostname }} was deregistrated from Load balancer, node name is {{ ansible_nodename }} >> /home/log.txt
  #  delegate_to: 127.0.0.1
 
 # - name: Create file1
 #   copy: 
 #     dest: /home/file1.txt
 #     content: |
 #       We are form Ukraine 
 #       Text Line1, in file1
 #       Text Line2. in file1
 #       Text Line3, {{ my text }}
 #   delegate_to: linux2

 # - name: Create file2
 #   copy: 
 #     dest: /home/file2.txt
 #     content: |
 #       Ghost of Kyiv
 #       Text Line2. in file2
 #       Text Line3, {{ my text }}

  - name: Reboot my Server
    shell: sleep 3 && reboot now
    async: 1
    poll: 0
  
  - name: Wait till my server will come up online
    wait_for:
        host: "{{ inventory_hostname }}"
        state: started
        delay: 5
        timeout: 40
    delegate_to: 127.0.0.1

